/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package principal;

public class App {
    

    public static void main(String[] args) {
        System.out.println("Hello, World!");
        System.out.println("Meu primeiro output!!");
    }
}
