/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoapp;

import java.sql.Connection;
import util.connectionFactory;

public class App {


    public static void main(String[] args) {
        Connection c = connectionFactory .getConnection();
        connectionFactory.closeConnection(c);
        
        Carro obj = new Carro();
    }
}
