/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heranca;

public class App {
   

    public static void main(String[] args) {
        
        Vendedor v = new Vendedor();
        v.getCpf();
        
        Motorista m = new Motorista();
    }
}
