/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heranca;

import java.util.Date;

public class App {
   

    public static void main(String[] args) {
        
        Vendedor v = new Vendedor();
        v.setNome("Cairo");
        v.setCpf("131313131332");
        v.setSalario(5000.0f);
        v.setDataNascimento( new Date());
        v.setComissaoPorItem(10.0f);
        v.setTotalItensVendidos(10);
        
        System.out.println("O salário do vendedor é: " + v.calcularSalario());
        
        Motorista m = new Motorista();
    }
}
